# Tomcat
server:
  # 端 口
  port: 8080
  # Servlet
  servlet:
    # Session
    session:
      # 超 时 时 间
      timeout: 120m

# Spring 配置
spring:
  session:
    timeout: 120m
  # Druid Pool 运行环境
  profiles:
    # 运 行 环 境
    active: dev
  # 工 作 流 程
  activiti:
    # 是 否 检 查 流 程 定 义 文 件
    check-process-definitions: false

# Mybatis 配 置
mybatis:
  # 配 置 扫 描
  mapper-locations: classpath*:**/xml/**.xml
  # 别 名 扫 描
  type-aliases-package: com.pearadmin

# Pear 插 件 配 置 信 息
pear:
  # Document 配 置 信 息
  swagger:
    # 文 档 标 题
    title: Pear Admin API
    # 是 否 开 启
    enable: true
    # 描 述 信 息
    describe: 企 业 快 速 开 发 平 台
    # 扫 包 路 径
    scan-package: com.pearadmin
    # 协 议
    licence: MIT
    # 协 议 地 址
    licence-url: https://gitee.com/pear-admin/Pear-Admin-Boot/blob/master/LICENSE
    # 组 织 信 息
    terms-of-service-url: https://gitee.com/pear-admin
    # 版 本 信 息
    version: Release 2.0.0
    # 扩 展 信 息
    contact:
      # 作 者
      name: 就 眠 儀 式
      # 连 接
      url: www.pearadmin.cn
      # 邮 箱
      email: Jmys1992@gmail.com
  # 权 限 配 置
  security:
    # 开 启 超 级 管 理 员 账 号 -- 不需要验证权限
    super-auth-open: true
    # 超 级 管 理 员 账 号 -- 不需要验证权限
    super-admin: admin
    # 允 许 同 一 账 号 多 端 登 录 个 数
    maximum: 1
    # 记 住 密 码 KEY
    remember-key: PEAR_REMEMBER
    # 不 需 要 权 限 拦 截 的 接 口 配 置
    open-api:
      - /login/**  # 开放登录接口
      - /system/captcha/** # 开放验证码接口
      - /assets/** # 开放静态资源
      - /admin/** # 开放静态资源
      - /component/** # 开放静态资源
      - /favicon.ico # 开放FAVICON

  # 上传配置
  upload:
    # windows 上传路径
    windows-path: D:\home\uploads\
    # linux 上传路径
    linux-path: /home/uploads/
    # 是否使用ftp服务器
    ftp-use: false
    #  ftp服务器地址
    hostname:
    # ftp服务器端口
    port: 0000
    # ftp服务器用户名
    username:
    # ftp服务器密码
    password:

# Page Helper 分页配置
pagehelper:
  # 方 言
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  config: classpath:logback-spring.xml



